[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NEXT_PUBLIC_API_URL = "https://fabulous-vitality-production-a112.up.railway.app"
  NEXT_PUBLIC_WS_URL = "wss://fabulous-vitality-production-a112.up.railway.app"
  NPM_FLAGS = "--legacy-peer-deps"

[[plugins]]
  package = "@netlify/plugin-nextjs"
